name: Build YTUHD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Download SDK
        run: |
          git clone --depth=1 https://github.com/theos/sdks.git ~/theos/sdks

      - name: Build Tweak
        run: |
          make clean package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YTUHD-DEB
          path: packages/*.deb
