name: Build YTUHD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Theos & SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          curl -LO https://github.com/theos/sdks/releases/download/v14.5/iPhoneOS14.5.sdk.tar.xz
          mkdir -p ~/theos/sdks
          tar -xf iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks
          rm iPhoneOS14.5.sdk.tar.xz

      - name: Build Tweak
        run: |
          make clean package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YTUHD-DEB
          path: packages/*.deb
